
language: ruby

sudo: required

services:
  - docker

before_install:
  - echo "testing123"

script:
  - docker ps -a

after_success:
  - echo "Success"

deploy:
  # trigger docker hub build
  provider: script
  on:
    tags: true
  script: curl --data source_type=Tag&source_name=$TRAVIS_TAG -X POST https://registry.hub.docker.com/u/sjoeboo/docker-yum-mirror/trigger/$DOCKER_KEY/
