
language: ruby

sudo: required

services:
  - docker

before_install:
  - echo "testing123"

script:
  - docker ps -a

after_success:
  - echo "Success"

deploy:
  # trigger docker hub build
  - provider: script
    on:
      tags: true
    script: bash trigger_docker_hub.sh $TRAVIS_TAG
